### ISSUE TITLE
start/stop scanner without stopping the asyncio loop

### ISSUE THREAD

**Issue by Snevzor** [frawau/aioblescan#11]
1. Without restarting the connection
This is possible by executing stop_scan_request(). The socket is still open in this case. To restart one can execute send_scan_request() but the scan parameters should be written again because between stop and start another BLE application can alter these params. This is related to https://github.com/frawau/aioblescan/issues/9.

So I think changing
```
    def send_scan_request(self):
        '''Sending LE scan request'''
        command=HCI_Cmd_LE_Scan_Enable(True,False)
        self.transport.write(command.encode())
```

to

```
    def send_scan_request(self):
        '''Sending LE scan request'''
        command=HCI_Cmd_LE_Set_Scan_Params()
        self.transport.write(command.encode())
        command=HCI_Cmd_LE_Scan_Enable(True,False)
        self.transport.write(command.encode())
```
Is a good idea.

2. By restarting the connection (closing the socket, re-opening the socket, new asyncio connection)
This would be useful not only to force restart but also in to restore the connection in case a disconnect event would arise.
I've tried some things but keep failing at this. Can someone give some pointers on how to achieve that?

**Comment by benjilev92** [comment]
I'm not into python in this but you can use a shell script where you use tmux to create a session where you launch aioblescan and with timeout you delete the session so it will rise a SIGINT (like CTRL + C) and will stop the ongoing scan. I've done that, check my gist https://gist.github.com/benjilev92/1e6d0777caa06a1f9614455ff086f844
