### ISSUE TITLE
reversed byte order on peer mac addresses on ARMv7

### ISSUE THREAD

**Issue by Anppa** [frawau/aioblescan#15]
python -m aioblescan -r on intel:

```
Weather info {'mac address': 'e6:e7:2e:1a:ab:2b', 'humidity': 59.0, 'temperature': 23.98, 'pressure': 102011, 'accelerometer': (16, -160, 988, 1000.9995004993759), 'voltage': 3043}
```

the same on ARMv7:
```
Weather info {'humidity': 59.0, 'voltage': 3043, 'rssi': -66, 'temperature': 23.98, 'mac address': '2b:ab:1a:2e:e7:e6', 'accelerometer': (16, -156, 992, 1004.3186745251728), 'pressure': 102001}
```

(edit: oops, I have the lastest from github on arm and latest from pypi on intel, not that it probably makes a difference)

**Comment by frawau** [comment]
Thanks for the bug report.

I am currently travelling, I'll have a look at it as soon as I can

**Comment by frawau** [comment]
OK. We have a problem, I tested and I don't see the problem. On my test I got the same MAC address on both x86_64 and armv7.

Could you run
    import sys
    sys.byteorder

in a Python3 shell

Also, what OSes are you running?

**Comment by Anppa** [comment]
It's a C.H.I.P. (getchip.com) running Allwinner R8. Byte order is 'little'. The thing runs debian jessie, with updated bluez 5.43 stack compiled from source. It could be also something weird with this hardware / drivers /whatnot. Luckily this is not a serious issue since it is easy to prepare for once you know it happens.

**Comment by frawau** [comment]
I tried on a RPi3 running Stretch.

You could try
    hcitool lescan

To see how the MAC address looks like.

**Comment by Anppa** [comment]
Argh, looks like it actually is my pull request (aioblescan.py:8) which causes the reversed byte order.

**Comment by frawau** [comment]
Can we close this issue?
