### ISSUE TITLE
TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by Baccos** [frawau/aioblescan#41]
https://github.com/frawau/aioblescan/blob/81057f2bd193ad2a826866b66ab2c6239984b2d7/aioblescan/aioblescan.py#L620

TypeError: object of type 'int' has no len()

**Comment by frawau** [comment]
Yes indeed... It looks like the "len" is not needed.... Can you tell me how you came across this issue please.

**Comment by frawau** [comment]
I pushed the fix. Can you please test it before I publish a new version.

**Comment by frawau** [comment]
Pushed 0.2.9 to pypi. If everything is OK, please close this issue.
