### ISSUE TITLE
Apple Air Tag detection?

### ISSUE THREAD

**Issue by createcandle** [frawau/aioblescan#47]
Can this library be used to detect Apple Air Tags?

**Comment by frawau** [comment]
I think it can, but you would need a plug-in to decode things

**Comment by Ernst79** [comment]
This is how we parse it in BLE monitor

https://github.com/Ernst79/bleparser/blob/master/package/bleparser/ibeacon.py

**Comment by Magalex2x14** [comment]
Apple AirTags is not iBeacons, unfortunately - https://www.beaconzone.co.uk/blog/are-apple-airtags-ibeacons/
